name: LaTeX

on:
  push:
    branches:
      - "master"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Compile
        uses: xu-cheng/latex-action@v3
        with:
          root_file: "*.tex"
      - name: Copy
        run: |
          mkdir public
          cp *.pdf public
      - name: Publish
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
